const dimensions=[
{name:"Strategy & Value",questions:["We can name the priority business problems AI should help solve.","Proposed AI initiatives connect to measurable organizational outcomes.","Leaders agree on where AI should—and should not—be used first."],recommendation:"Choose one high-value, bounded problem. Define its owner, users, baseline, success measure, and why AI is preferable to a simpler intervention."},
{name:"Leadership & Governance",questions:["A named leader is accountable for AI decisions and outcomes.","We have a process for approving, monitoring, and stopping AI use cases.","Policies address privacy, security, bias, transparency, and human oversight."],recommendation:"Create a lightweight AI governance charter covering ownership, acceptable use, risk tiers, review gates, escalation, and human accountability."},
{name:"Data & Technology",questions:["The data needed for priority use cases is accessible, reliable, and appropriately governed.","Our systems can integrate with new tools without excessive manual work.","We understand relevant privacy, security, vendor, and infrastructure constraints."],recommendation:"Audit the data and system dependencies for one priority use case. Resolve ownership, quality, access, integration, and security gaps before procurement."},
{name:"Processes & Workflows",questions:["Priority workflows are documented well enough to identify friction and redesign opportunities.","We understand which steps require human judgment and which may be assisted or automated.","Process owners can explain how an AI-enabled workflow would change roles, handoffs, and controls."],recommendation:"Map one workflow end to end. Mark delays, repetitive tasks, decision points, exceptions, data inputs, and required human review before selecting a tool."},
{name:"People & Adoption",questions:["Employees understand how AI may affect their work and have channels to raise concerns.","Teams have the skills and protected time needed to test and adopt AI responsibly.","Change, training, support, and feedback are planned—not treated as post-launch activities."],recommendation:"Form a small cross-functional pilot team. Pair role-specific training with office hours, feedback loops, adoption measures, and explicit protection for human judgment."},
{name:"Measurement & Learning",questions:["Each AI initiative has baseline measures and clear success criteria.","We can monitor quality, errors, adoption, cost, risk, and unintended effects after launch.","Pilot findings are documented and used to decide whether to improve, scale, pause, or stop."],recommendation:"Define a pilot scorecard before launch: outcome, quality, adoption, cost, risk, and learning metrics, plus a date and owner for the scale-or-stop decision."}
];
const labels=["Not in place","Early or informal","Defined and partly consistent","Established and evidenced"];
const qs=document.querySelector("#questions");
dimensions.forEach((d,di)=>{const field=document.createElement("fieldset");field.innerHTML="<legend>"+(di+1)+". "+d.name+"</legend>";d.questions.forEach((q,qi)=>{const id="q"+di+"_"+qi;const block=document.createElement("div");block.className="question";block.innerHTML="<p>"+q+"</p>"+labels.map((l,i)=>'<label class="option"><input type="radio" name="'+id+'" value="'+(i+1)+'"> '+(i+1)+". "+l+"</label>").join("");field.appendChild(block)});qs.appendChild(field)});
const form=document.querySelector("#assessment"),intro=document.querySelector("#intro"),results=document.querySelector("#results");
document.querySelector("#start").onclick=()=>{intro.classList.add("hidden");form.classList.remove("hidden");form.scrollIntoView({behavior:"smooth"})};
form.addEventListener("change",()=>{const n=form.querySelectorAll("input:checked").length;document.querySelector("#progress").value=n;document.querySelector("#progressText").textContent=n+" of 18 answered"});
form.addEventListener("submit",e=>{e.preventDefault();const selected=[...form.querySelectorAll("input:checked")];if(selected.length<18){document.querySelector("#formError").textContent="Please answer all 18 questions before viewing your result.";return}document.querySelector("#formError").textContent="";const scores=dimensions.map((d,di)=>{const total=d.questions.reduce((sum,q,qi)=>sum+Number(form.elements["q"+di+"_"+qi].value),0);return Math.round((total-3)/9*100)});const overall=Math.round(scores.reduce((a,b)=>a+b,0)/scores.length);const low=Math.min(...scores),high=Math.max(...scores),lowIndex=scores.indexOf(low),highIndex=scores.indexOf(high);const stage=overall<25?"Exploring":overall<50?"Emerging":overall<75?"Developing":"Scaling-ready";results.innerHTML='<p class="eyebrow" style="color:#155eef">Rapid diagnostic result</p><div class="score">'+overall+'/100</div><p class="stage">'+stage+'</p><p>Your strongest current capability is <strong>'+dimensions[highIndex].name+'</strong>. Your priority constraint is <strong>'+dimensions[lowIndex].name+'</strong>.</p><div class="bars">'+dimensions.map((d,i)=>'<div class="bar-row"><span>'+d.name+'</span><div class="track"><div class="fill" style="width:'+scores[i]+'%"></div></div><strong>'+scores[i]+'%</strong></div>').join("")+'</div><div class="recommendation"><strong>Recommended first move</strong><p>'+dimensions[lowIndex].recommendation+'</p></div><p><strong>Interpretation:</strong> A score is a conversation starter, not proof of readiness. Validate it with people closest to the work and with operational evidence.</p><div class="actions"><button type="button" onclick="window.print()">Print results</button><button class="secondary" type="button" onclick="location.reload()">Retake assessment</button></div>';form.classList.add("hidden");results.classList.remove("hidden");results.scrollIntoView({behavior:"smooth"})});